version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.5
  - dependency-name: cssnano
    versions:
    - 4.1.11
    - 5.0.0
    - 5.0.1
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.39.1
    - 2.41.1
    - 2.41.4
    - 2.42.3
    - 2.44.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: uglify-js
    versions:
    - 3.13.2
  - dependency-name: eslint
    versions:
    - 7.22.0
  - dependency-name: svgo
    versions:
    - 2.0.0
    - 2.0.3
    - 2.1.0
    - 2.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.5
    - 7.13.8
  - dependency-name: tape
    versions:
    - 5.2.0
    - 5.2.1
