addons:
  firefox: 'latest'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
cache:
  bundler: true
  directories:
    - node_modules
language: node_js
node_js:
  - '6'
  - 'stable'
os:
  - linux
  - osx
sudo: false
