addons:
  firefox: '48'
before_install: # before_script
  # - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ls /Applications/; fi
  # - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cask install google-chrome; fi
before_script:
  - echo "start npm stuff";
cache:
  bundler: true
  directories:
    - node_modules
language: node_js
node_js:
  - '6'
#  - 'stable'
os:
  - linux
  - osx
sudo: false
